### PR TITLE
Rename `master` branch to `1.x` and update installation instructions

### PR DESCRIPTION
**Pull request by clue**
Builds on top of #166
Refs https://github.com/reactphp/async/pull/29

### CODE REVIEW

**Comment by llaville** [comment]
@clue Don't forget to update also https://github.com/graphp/graphviz/blob/master/composer.json#L13 to be able to install `graphp/graphviz` package too !

**Comment by clue** [comment]
@llaville Good catch, will make sure this is updated across the @GraPHP organization once this PR is merged! GitHub automatically sets up redirects for old branch names, so I think the previous installations should continue to work in either case.

**Review by SimonFrings — APPROVED** [review]

**Comment by llaville** [comment]
> GitHub automatically sets up redirects for old branch names, so I think the previous installations should continue to work in either case.

@clue No it does not works when you add constraint on version with alias into a composer.json file like that : 
```
    "require": {
        "php": "^7.4.0 || ^8.0",
        "graphp/graph": "1.x-dev#41e73a5 as 1.0.0",
        "graphp/graphviz": "dev-master#42a2098 as 1.0.0"
    },
```

Composer 2.4 prints
```
  Problem 1
    - Root composer.json requires graphp/graphviz dev-master#42a2098 as 1.0.0 -> satisfiable by graphp/graphviz[dev-master].
    - graphp/graphviz dev-master requires graphp/graph dev-master#214de45 as 1.0.0 -> found graphp/graph[dev-master] but it conflicts with your root composer.json require (1.x-dev#41e73a5 as 1.0.0).
```

So, please apply change on graphviz package ASAP !

**Comment by clue** [comment]
@llaville See https://github.com/graphp/graphviz/pull/64.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️

**Pull request merged**
